/** Local copies of Figma MCP assets (7-day remote URLs replaced for persistence). */
export const assets = {
  checkboxOutline: "/figma-assets/checkbox-outline.svg",
  checkboxChecked: "/figma-assets/checkbox-checked.svg",
  resizeHandle: "/figma-assets/resize-handle.svg",
  docElectronic: "/figma-assets/doc-electronic.png",
  docRecord: "/figma-assets/doc-record.png",
  docLegacy: "/figma-assets/doc-legacy.png",
  radioChecked: "/figma-assets/radio-checked.svg",
  radioUnchecked: "/figma-assets/radio-unchecked.svg",
  iconQuestion: "/figma-assets/icon-question.svg",
  iconCamera: "/figma-assets/icon-camera.svg",
  logoKatix: "/figma-assets/logo-katix.png",
  logoKatixFooter: "/figma-assets/logo-katix-footer.png",
  bikeFront: "/figma-assets/bike-front.png",
  skeletonRear: "/figma-assets/skeleton-rear.png",
  skeletonLeft: "/figma-assets/skeleton-left.png",
  skeletonRight: "/figma-assets/skeleton-right.png",
  skeletonOdometer: "/figma-assets/skeleton-odometer.png",
  skeletonScratch: "/figma-assets/skeleton-scratch.png",
  carSkeletonScratch: "/figma-assets/car-skeleton-scratch.png",
  carDamagePlus: "/figma-assets/car-damage-plus.png",
  skeletonCustom: "/figma-assets/skeleton-custom.png",
  iconPlus: "/figma-assets/icon-plus.svg",
  iconPhone: "/figma-assets/icon-phone.svg",
  guideSun: "/figma-assets/guide-sun.svg",
  guideShakensho: "/figma-assets/guide-shakensho.png",
  guideSampleFront: "/figma-assets/guide-samples/sample-front.png",
  guideSampleRear: "/figma-assets/guide-samples/sample-rear.png",
  guideSampleLeft: "/figma-assets/guide-samples/sample-left.png",
  guideSampleRight: "/figma-assets/guide-samples/sample-right.png",
  guideSampleOdometer: "/figma-assets/guide-samples/sample-odometer.png",
  guideSampleOdometerNg: "/figma-assets/guide-samples/sample-odometer-ng.png",
} as const;
